name: po2lmo

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/po2lmo.yml'

jobs:

  i18n:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: build
        run: |
          wget https://github.com/kongfl888/luci-app-kcpufreq/raw/master/po/zh-cn/kcpufreq.po
          mkdir -p ./i18n/
          po2lmo kcpufreq.po ./i18n/kcpufreq.zh-cn.lmo

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: i18n
          path: ./i18n/
